# Setup
name:         CK'Pages
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      /MyPages
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
